services:
  capacitaciones_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: proyecto_capacitaciones_laravel13:local
    container_name: capacitaciones_laravel13
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env.docker
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/framework/sessions:/var/www/html/storage/framework/sessions
    extra_hosts:
      - "host.docker.internal:host-gateway"