:setvar APP_DB_USERNAME "capacitaciones_runtime"

USE [db_capacitaciones_stb];
GO

IF USER_ID(N'$(APP_DB_USERNAME)') IS NULL
    THROW 50001, 'Cree primero el LOGIN y USER de ejecución con una contraseña segura.', 1;
GO

IF IS_ROLEMEMBER(N'db_owner', N'$(APP_DB_USERNAME)') = 1
    ALTER ROLE [db_owner] DROP MEMBER [$(APP_DB_USERNAME)];
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::dbo TO [$(APP_DB_USERNAME)];
GRANT EXECUTE ON SCHEMA::dbo TO [$(APP_DB_USERNAME)];
DENY ALTER, TAKE OWNERSHIP ON SCHEMA::dbo TO [$(APP_DB_USERNAME)];
DENY CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, ALTER ANY SCHEMA TO [$(APP_DB_USERNAME)];
GO
