upload_max_filesize=250M
post_max_size=260M
memory_limit=512M
max_execution_time=300
max_input_time=300
max_input_vars=10000

date.timezone=America/Tegucigalpa

display_errors=Off
log_errors=On
error_reporting=E_ALL

expose_php=Off
session.cookie_httponly=1
